"""shop and config table added

Revision ID: b06ee2ea9201
Revises: 
Create Date: 2025-07-16 12:12:57.436311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b06ee2ea9201'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('botConfig',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bot_clinetId', sa.String(), nullable=True),
    sa.Column('bot_secretKey', sa.String(), nullable=True),
    sa.Column('redirect_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shops',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone_number_id', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('verify_token', sa.String(), nullable=False),
    sa.Column('bitcommerz_access_token', sa.String(), nullable=True),
    sa.Column('bitcommerz_refresh_token', sa.String(), nullable=True),
    sa.Column('bitcommerz_token_expires_in', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number_id'),
    sa.UniqueConstraint('verify_token')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shops')
    op.drop_table('botConfig')
    # ### end Alembic commands ###
