"""redirecturl

Revision ID: ebce95a6ab67
Revises: 863f880715bf
Create Date: 2025-07-10 12:06:44.702569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebce95a6ab67'
down_revision: Union[str, Sequence[str], None] = '863f880715bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('botConfig', sa.Column('redirect_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('botConfig', 'redirect_url')
    # ### end Alembic commands ###
